"""French token mappings for business column display names."""

from __future__ import annotations

FRENCH_COLUMN_TOKEN_MAP: dict[str, str] = {
    # Dates et temporalite
    "annee": "Année",
    "annees": "Années",
    "debut": "Début",
    "echeance": "Échéance",
    "periode": "Période",
    "duree": "Durée",
    "cree": "Créée",
    "creation": "Création",
    "modifie": "Modifiée",
    "modification": "Modification",
    "maj": "Màj",
    "ajuste": "Ajusté",
    "ajustee": "Ajustée",
    "confirme": "Confirmé",
    "confirmee": "Confirmée",
    "bloque": "Bloqué",
    "bloquee": "Bloquée",
    "livre": "Livré",
    "livree": "Livrée",
    "preleve": "Prélevé",
    "prelevee": "Prélevée",
    "activite": "Activité",
    "capacite": "Capacité",
    "echelonne": "Échelonné",
    "echelonnee": "Échelonnée",
    "traite": "Traité",
    "traitee": "Traitée",
    "execute": "Exécuté",
    "executee": "Exécutée",
    "execution": "Exécution",
    "verifie": "Vérifié",
    "verifiee": "Vérifiée",
    "verification": "Vérification",
    "nonconforme": "Non-Conforme",
    "expedie": "Expédié",
    "expediee": "Expédiée",
    "reception": "Réception",
    "reserve": "Réservé",
    "reservee": "Réservée",
    "disponibilite": "Disponibilité",
    "facture": "Facturé",
    "facturee": "Facturée",
    "regle": "Réglé",
    "reglee": "Réglée",
    "impaye": "Impayé",
    "impayee": "Impayée",
    # Metier, qualite, statut
    "etat": "État",
    "libelle": "Libellé",
    "categorie": "Catégorie",
    "detail": "Détail",
    "resume": "Résumé",
    "priorite": "Priorité",
    "qualite": "Qualité",
    "tolerance": "Tolérance",
    "rejetee": "Rejetée",
    "validee": "Validée",
    "fermee": "Fermée",
    "cloture": "Clôture",
    # Quantites, montants, unites
    "qte": "Qté",
    "quantite": "Quantité",
    "quantites": "Quantités",
    "cout": "Coût",
    "couts": "Coûts",
    "ecart": "Écart",
    "unite": "Unité",
    "unites": "Unités",
    # Logistique et inventaire
    "entree": "Entrée",
    "arrivee": "Arrivée",
    "depart": "Départ",
    "region": "Région",
    "entrepot": "Entrepôt",
    "reference": "Référence",
    "element": "Élément",
    "elements": "Éléments",
    # Technique et identifiants
    "id": "ID",
    "ids": "IDs",
    "uuid": "UUID",
    "api": "API",
    "url": "URL",
    "ip": "IP",
    "sql": "SQL",
    "etl": "ETL",
    "ttc": "TTC",
    "ht": "HT",
    "tva": "TVA",
    "numero": "Numéro",
    "num": "N°",
}
